//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifteenGameDbFirstRepository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentGameCell
    {
        public long Id { get; set; }
        public int CurrentGameId { get; set; }
        public int CellIndex { get; set; }
        public int CellValue { get; set; }
    
        public virtual CurrentGame CurrentGame { get; set; }
    }
}
