//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifteenGameDbFirstRepository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurrentGame()
        {
            this.CurrentGameCells = new HashSet<CurrentGameCell>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime GameStartTime { get; set; }
        public int MoveCount { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentGameCell> CurrentGameCells { get; set; }
        public virtual User User { get; set; }
    }
}
