// <auto-generated />
namespace FifteenGameCodeFirstRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddField));
        
        string IMigrationMetadata.Id
        {
            get { return "202012090429541_AddField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
